#!/usr/bin/env bash
#
# sandbox/firecracker/vm.sh
#
# Runtime helpers for the Firecracker sandbox.
# Sourced by clawfactory.sh when SANDBOX_MODE=firecracker.
#
# Provides: fc_ensure_lima, fc_setup_network, fc_start_vm, fc_stop_vm,
#           fc_ssh, fc_exec, fc_sync, fc_build, fc_services,
#           fc_forward_ports, fc_status

# --- Configuration (must match setup.sh) ---
FC_LIMA_VM="clawfactory-fc"
FC_TAP_DEV="tap0"
FC_GUEST_IP="172.16.0.2"
FC_HOST_IP="172.16.0.1"
FC_GUEST_MAC="AA:FC:00:00:00:01"
FC_DIR="/opt/firecracker"

# Read VM password from secrets (generated by setup.sh)
FC_PASSWORD_FILE="${SCRIPT_DIR}/secrets/firecracker.password"
if [[ -f "$FC_PASSWORD_FILE" ]]; then
    FC_ROOT_PASSWORD=$(cat "$FC_PASSWORD_FILE")
else
    echo "Error: VM password not found at ${FC_PASSWORD_FILE}" >&2
    echo "Run ./sandbox/firecracker/setup.sh first." >&2
    # Don't exit here since this file is sourced — just set empty
    FC_ROOT_PASSWORD=""
fi

# Read sizing from secrets (generated by setup.sh)
FC_SIZING_FILE="${SCRIPT_DIR}/secrets/firecracker.sizing"
FC_VCPUS=4
FC_MEM_MIB=4096
if [[ -f "$FC_SIZING_FILE" ]]; then
    source "$FC_SIZING_FILE"
fi

# Port forwarding (macOS -> Lima -> Firecracker)
FC_GATEWAY_PORT="${GATEWAY_PORT:-18789}"
FC_CONTROLLER_PORT="${CONTROLLER_PORT:-8080}"

# --- Internal helpers ---
_fc_lima_exec() {
    limactl shell "$FC_LIMA_VM" -- "$@"
}

_fc_lima_root() {
    limactl shell "$FC_LIMA_VM" -- sudo bash -c "$1"
}

# ============================================================
# fc_ensure_lima — Start Lima VM if not running
# ============================================================
fc_ensure_lima() {
    if ! command -v limactl >/dev/null 2>&1; then
        echo "Error: limactl not found. Run: ./sandbox/firecracker/setup.sh" >&2
        return 1
    fi

    if ! limactl list -q 2>/dev/null | grep -q "^${FC_LIMA_VM}$"; then
        echo "Error: Lima VM '${FC_LIMA_VM}' not found. Run: ./sandbox/firecracker/setup.sh" >&2
        return 1
    fi

    local status
    status=$(limactl list --json 2>/dev/null | python3 -c "
import json,sys
for vm in json.loads(sys.stdin.read().rstrip().replace('}\n{', '},{')):
    if vm.get('name')=='$FC_LIMA_VM': print(vm.get('status',''))
" 2>/dev/null || echo "unknown")

    if [ "$status" = "Running" ]; then
        return 0
    fi

    echo "Starting Lima VM '${FC_LIMA_VM}'..."
    limactl start "$FC_LIMA_VM"
    echo "Lima VM started"
}

# ============================================================
# fc_setup_network — Create TAP device and enable NAT
# ============================================================
fc_setup_network() {
    echo "Setting up network (TAP + NAT)..."
    _fc_lima_root "
        # Clean up existing
        ip link del ${FC_TAP_DEV} 2>/dev/null || true

        # Create TAP
        ip tuntap add ${FC_TAP_DEV} mode tap
        ip addr add ${FC_HOST_IP}/24 dev ${FC_TAP_DEV}
        ip link set ${FC_TAP_DEV} up

        # Enable forwarding + NAT
        echo 1 > /proc/sys/net/ipv4/ip_forward
        DEFAULT_IF=\$(ip route | grep default | awk '{print \$5}' | head -1)
        iptables -t nat -C POSTROUTING -o \$DEFAULT_IF -j MASQUERADE 2>/dev/null || \
            iptables -t nat -A POSTROUTING -o \$DEFAULT_IF -j MASQUERADE
        iptables -C FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || \
            iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
        iptables -C FORWARD -i ${FC_TAP_DEV} -o \$DEFAULT_IF -j ACCEPT 2>/dev/null || \
            iptables -A FORWARD -i ${FC_TAP_DEV} -o \$DEFAULT_IF -j ACCEPT
    "
    echo "Network ready: ${FC_TAP_DEV} (${FC_HOST_IP} <-> ${FC_GUEST_IP})"
}

# ============================================================
# fc_start_vm — Launch Firecracker microVM and wait for SSH
# ============================================================
fc_start_vm() {
    # Check if already running
    if _fc_lima_root "test -f ${FC_DIR}/fc.pid && kill -0 \$(cat ${FC_DIR}/fc.pid) 2>/dev/null" 2>/dev/null; then
        echo "Firecracker VM already running"
        return 0
    fi

    echo "Starting Firecracker microVM..."

    # Write VM config
    _fc_lima_exec bash -c "
        cat > ${FC_DIR}/vm-config.json <<'VMCFG'
{
  \"boot-source\": {
    \"kernel_image_path\": \"${FC_DIR}/vmlinux\",
    \"boot_args\": \"console=ttyS0 reboot=k panic=1 pci=off root=/dev/vda rw init=/sbin/init\"
  },
  \"drives\": [{
    \"drive_id\": \"rootfs\",
    \"path_on_host\": \"${FC_DIR}/rootfs.ext4\",
    \"is_root_device\": true,
    \"is_read_only\": false
  }],
  \"network-interfaces\": [{
    \"iface_id\": \"eth0\",
    \"guest_mac\": \"${FC_GUEST_MAC}\",
    \"host_dev_name\": \"${FC_TAP_DEV}\"
  }],
  \"machine-config\": {
    \"vcpu_count\": ${FC_VCPUS},
    \"mem_size_mib\": ${FC_MEM_MIB}
  }
}
VMCFG
    "

    # Clean up old socket
    _fc_lima_root "rm -f /tmp/firecracker.socket"

    # Launch Firecracker
    _fc_lima_root "
        firecracker \
            --api-sock /tmp/firecracker.socket \
            --config-file ${FC_DIR}/vm-config.json \
            > ${FC_DIR}/boot.log 2>&1 &
        echo \$! > ${FC_DIR}/fc.pid
    "

    # Wait for SSH
    echo "Waiting for VM to boot..."
    local retries=60
    for i in $(seq 1 "$retries"); do
        if fc_exec "true" 2>/dev/null; then
            echo "Firecracker VM ready (${i}s)"
            return 0
        fi
        sleep 1
    done

    echo "Error: VM SSH did not come up after ${retries}s" >&2
    echo "Check boot log: limactl shell ${FC_LIMA_VM} -- cat ${FC_DIR}/boot.log" >&2
    return 1
}

# ============================================================
# fc_stop_vm — Kill Firecracker process and cleanup
# ============================================================
fc_stop_vm() {
    echo "Stopping Firecracker VM..."

    # Kill port-forwarding socat processes
    _fc_lima_root "pkill -f 'socat.*172\.16\.0\.2' 2>/dev/null || true" 2>/dev/null || true

    # Stop Firecracker
    _fc_lima_root "
        if [ -f ${FC_DIR}/fc.pid ]; then
            kill \$(cat ${FC_DIR}/fc.pid) 2>/dev/null || true
            rm -f ${FC_DIR}/fc.pid /tmp/firecracker.socket
        fi
        # Kill any orphaned firecracker processes
        pkill -f firecracker 2>/dev/null || true
        # Clean up TAP device
        ip link del ${FC_TAP_DEV} 2>/dev/null || true
    " 2>/dev/null || true

    # Clean up any leftover chroot mounts (from setup.sh or crashed builds)
    _fc_lima_root "
        for mp in /mnt/fc-rootfs/dev /mnt/fc-rootfs/proc /mnt/fc-rootfs/sys; do
            mountpoint -q \$mp 2>/dev/null && umount -l \$mp 2>/dev/null || true
        done
        mountpoint -q /mnt/fc-rootfs 2>/dev/null && umount -l /mnt/fc-rootfs 2>/dev/null || true
    " 2>/dev/null || true

    echo "Firecracker VM stopped"
}

# ============================================================
# fc_ssh — Interactive SSH into Firecracker VM
# ============================================================
fc_ssh() {
    [[ -n "$FC_ROOT_PASSWORD" ]] || { echo "Error: VM password not set. Run setup.sh first." >&2; return 1; }
    _fc_lima_exec sshpass -p "$FC_ROOT_PASSWORD" ssh \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o LogLevel=ERROR \
        "root@${FC_GUEST_IP}"
}

# ============================================================
# fc_exec — Run a command inside Firecracker VM
# ============================================================
fc_exec() {
    [[ -n "$FC_ROOT_PASSWORD" ]] || { echo "Error: VM password not set. Run setup.sh first." >&2; return 1; }
    _fc_lima_exec sshpass -p "$FC_ROOT_PASSWORD" ssh \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o LogLevel=ERROR \
        -o ConnectTimeout=10 \
        "root@${FC_GUEST_IP}" "$@"
}

# ============================================================
# fc_sync — Rsync ClawFactory files into Firecracker VM
# ============================================================
fc_sync() {
    local instance="${INSTANCE_NAME:-default}"
    echo "Syncing ClawFactory files to Firecracker VM (instance: ${instance})..."

    # Rsync from Lima host to Firecracker guest via TAP network
    # Lima can see the macOS filesystem via mounts, but we've disabled mounts,
    # so we first need to get files into Lima, then into Firecracker.
    #
    # Strategy: Use limactl copy or rsync through Lima's SSH.
    # Since Lima mounts are disabled, we rsync from macOS -> Lima -> Firecracker.

    local cf_root="${SCRIPT_DIR}"

    # Step 1: Copy files to a staging area in Lima
    local lima_staging="/tmp/cf-sync"
    _fc_lima_exec mkdir -p "$lima_staging"

    # rsync from macOS to Lima (limactl handles the transport)
    limactl copy --recursive \
        "${cf_root}/controller" \
        "${FC_LIMA_VM}:${lima_staging}/controller" 2>/dev/null || \
    _fc_lima_exec rsync -a --delete "${cf_root}/controller/" "${lima_staging}/controller/"

    limactl copy --recursive \
        "${cf_root}/proxy" \
        "${FC_LIMA_VM}:${lima_staging}/proxy" 2>/dev/null || \
    _fc_lima_exec rsync -a --delete "${cf_root}/proxy/" "${lima_staging}/proxy/"

    # Copy bot_repos for this instance
    if [[ -d "${cf_root}/bot_repos/${instance}" ]]; then
        _fc_lima_exec mkdir -p "${lima_staging}/bot_repos/${instance}"
        limactl copy --recursive \
            "${cf_root}/bot_repos/${instance}/approved" \
            "${FC_LIMA_VM}:${lima_staging}/bot_repos/${instance}/approved" 2>/dev/null || true
    fi

    # Copy secrets for this instance
    if [[ -d "${cf_root}/secrets/${instance}" ]]; then
        _fc_lima_exec mkdir -p "${lima_staging}/secrets/${instance}"
        limactl copy --recursive \
            "${cf_root}/secrets/${instance}" \
            "${FC_LIMA_VM}:${lima_staging}/secrets/${instance}" 2>/dev/null || true
    fi

    # Step 2: Rsync from Lima staging to Firecracker guest
    [[ -n "$FC_ROOT_PASSWORD" ]] || { echo "Error: VM password not set. Run setup.sh first." >&2; return 1; }
    _fc_lima_exec sshpass -p "$FC_ROOT_PASSWORD" rsync -az --delete \
        --exclude '.git' \
        --exclude 'node_modules' \
        --exclude 'bot_repos/*/state/installed' \
        --exclude 'snapshots' \
        --exclude '.DS_Store' \
        --exclude '__pycache__' \
        -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR" \
        "${lima_staging}/" "root@${FC_GUEST_IP}:/srv/clawfactory/"

    # Ensure directory structure exists inside VM
    fc_exec "mkdir -p /srv/clawfactory/bot_repos/${instance}/state \
                      /srv/clawfactory/audit \
                      /srv/clawfactory/snapshots/${instance}"

    # Copy nginx config to the right place
    fc_exec "cp /srv/clawfactory/proxy/nginx.conf /etc/nginx/sites-available/clawfactory 2>/dev/null || true"

    # Clean up staging
    _fc_lima_exec rm -rf "$lima_staging"

    echo "Files synced to Firecracker VM"
}

# ============================================================
# fc_build — Build OpenClaw and install deps inside VM
# ============================================================
fc_build() {
    local instance="${INSTANCE_NAME:-default}"
    echo "Building inside Firecracker VM (instance: ${instance})..."

    # Build OpenClaw gateway (if package.json exists)
    fc_exec "
        cd /srv/clawfactory/bot_repos/${instance}/approved
        if [ -f package.json ]; then
            echo '[build] Installing Node.js dependencies...'
            if command -v pnpm >/dev/null 2>&1; then
                pnpm install --frozen-lockfile 2>/dev/null || pnpm install
            else
                npm install
            fi

            echo '[build] Building OpenClaw...'
            if command -v pnpm >/dev/null 2>&1; then
                pnpm build 2>/dev/null || npm run build
            else
                npm run build
            fi
            echo '[build] OpenClaw built'
        else
            echo '[build] No package.json found, skipping Node.js build'
        fi
    "

    # Install controller pip deps
    fc_exec "
        if [ -f /srv/clawfactory/controller/requirements.txt ]; then
            echo '[build] Installing Python dependencies...'
            pip3 install --break-system-packages -r /srv/clawfactory/controller/requirements.txt 2>/dev/null
            echo '[build] Python dependencies installed'
        fi
    "

    echo "Build complete"
}

# ============================================================
# fc_services — Start/stop/restart systemd services inside VM
# ============================================================
fc_services() {
    local action="${1:-start}"
    local instance="${INSTANCE_NAME:-default}"

    # Create instance-specific systemd overrides
    fc_exec "
        # Gateway override
        mkdir -p /etc/systemd/system/openclaw-gateway.service.d
        cat > /etc/systemd/system/openclaw-gateway.service.d/instance.conf <<EOF
[Service]
WorkingDirectory=/srv/clawfactory/bot_repos/${instance}/approved
EnvironmentFile=/srv/clawfactory/secrets/${instance}/gateway.env
Environment=INSTANCE_NAME=${instance}
Environment=OPENCLAW_GATEWAY_MODE=local
Environment=OPENCLAW_GATEWAY_AUTH=none
EOF

        # Controller override (uvicorn on 8081, nginx proxies 8080->8081)
        mkdir -p /etc/systemd/system/clawfactory-controller.service.d
        cat > /etc/systemd/system/clawfactory-controller.service.d/instance.conf <<EOF
[Service]
WorkingDirectory=/srv/clawfactory/controller
EnvironmentFile=/srv/clawfactory/secrets/${instance}/controller.env
Environment=APPROVED_DIR=/srv/clawfactory/bot_repos/${instance}/approved
Environment=OPENCLAW_HOME=/srv/clawfactory/bot_repos/${instance}/state
Environment=AUDIT_LOG=/srv/clawfactory/audit/audit.jsonl
Environment=INSTANCE_NAME=${instance}
Environment=GATEWAY_CONTAINER=local
Environment=SNAPSHOTS_DIR=/srv/clawfactory/snapshots/${instance}
Environment=AGE_KEY=/srv/clawfactory/secrets/${instance}/snapshot.key
ExecStart=
ExecStart=/usr/bin/python3 -m uvicorn main:app --host 0.0.0.0 --port 8081
EOF

        systemctl daemon-reload
    "

    case "$action" in
        start)
            echo "Starting ClawFactory services..."
            fc_exec "systemctl start openclaw-gateway clawfactory-controller nginx docker"
            echo "Services started"
            ;;
        stop)
            echo "Stopping ClawFactory services..."
            fc_exec "systemctl stop openclaw-gateway clawfactory-controller nginx" 2>/dev/null || true
            echo "Services stopped"
            ;;
        restart)
            echo "Restarting ClawFactory services..."
            fc_exec "systemctl restart openclaw-gateway clawfactory-controller nginx"
            echo "Services restarted"
            ;;
        status)
            fc_exec "systemctl status --no-pager openclaw-gateway clawfactory-controller nginx docker" 2>/dev/null || true
            ;;
        *)
            echo "Usage: fc_services {start|stop|restart|status}" >&2
            return 1
            ;;
    esac
}

# ============================================================
# fc_forward_ports — Forward ports from Lima to Firecracker
# ============================================================
fc_forward_ports() {
    echo "Setting up port forwarding..."

    # Kill existing socat forwarders
    _fc_lima_root "pkill -f 'socat.*${FC_GUEST_IP}' 2>/dev/null || true"

    # Forward gateway port: Lima 0.0.0.0:GATEWAY_PORT -> FC guest:80 (nginx)
    _fc_lima_root "
        socat TCP-LISTEN:${FC_GATEWAY_PORT},fork,reuseaddr TCP:${FC_GUEST_IP}:80 &
        echo \"Port ${FC_GATEWAY_PORT} -> ${FC_GUEST_IP}:80 (gateway via nginx)\"
    "

    # Forward controller port: Lima 0.0.0.0:CONTROLLER_PORT -> FC guest:8080 (nginx -> controller)
    _fc_lima_root "
        socat TCP-LISTEN:${FC_CONTROLLER_PORT},fork,reuseaddr TCP:${FC_GUEST_IP}:8080 &
        echo \"Port ${FC_CONTROLLER_PORT} -> ${FC_GUEST_IP}:8080 (controller via nginx)\"
    "

    # Lima's VZ host agent auto-forwards ports that Lima listens on to macOS
    echo "Port forwarding active:"
    echo "  macOS:${FC_GATEWAY_PORT} -> Lima -> Firecracker:80 (gateway)"
    echo "  macOS:${FC_CONTROLLER_PORT} -> Lima -> Firecracker:8080 (controller)"
}

# ============================================================
# fc_status — Check VM and service status
# ============================================================
fc_status() {
    echo "=== Firecracker Sandbox Status ==="
    echo ""

    # Lima VM status
    echo "Lima VM:"
    if limactl list -q 2>/dev/null | grep -q "^${FC_LIMA_VM}$"; then
        local status
        status=$(limactl list --json 2>/dev/null | python3 -c "
import json,sys
for vm in json.loads(sys.stdin.read().rstrip().replace('}\n{', '},{')):
    if vm.get('name')=='$FC_LIMA_VM': print(vm.get('status',''))
" 2>/dev/null || echo "unknown")
        echo "  ${FC_LIMA_VM}: ${status}"
    else
        echo "  Not provisioned (run ./sandbox/firecracker/setup.sh)"
        return 1
    fi

    # Firecracker VM status
    echo ""
    echo "Firecracker VM:"
    if _fc_lima_root "test -f ${FC_DIR}/fc.pid && kill -0 \$(cat ${FC_DIR}/fc.pid) 2>/dev/null" 2>/dev/null; then
        echo "  Running (PID: $(_fc_lima_root "cat ${FC_DIR}/fc.pid"))"
        echo "  Guest IP: ${FC_GUEST_IP}"
    else
        echo "  Not running"
        return 0
    fi

    # Service status
    echo ""
    echo "Services:"
    for svc in openclaw-gateway clawfactory-controller nginx docker; do
        local svc_status
        svc_status=$(fc_exec "systemctl is-active $svc" 2>/dev/null || echo "unknown")
        printf "  %-30s %s\n" "$svc" "$svc_status"
    done

    # Port forwarding
    echo ""
    echo "Port forwarding:"
    local socat_count
    socat_count=$(_fc_lima_root "pgrep -c -f 'socat.*${FC_GUEST_IP}'" 2>/dev/null || echo "0")
    if [[ "$socat_count" -gt 0 ]]; then
        echo "  Active (${socat_count} forwarders)"
        echo "  Gateway:    http://localhost:${FC_GATEWAY_PORT}"
        echo "  Controller: http://localhost:${FC_CONTROLLER_PORT}"
    else
        echo "  Not active"
    fi
}
