#!/usr/bin/env bash
#
# sandbox/lima/setup.sh
#
# One-time provisioning: Lima VM with ClawFactory dependencies.
#
# Stack: macOS -> Lima (VZ framework) -> services as systemd units
#   Inside the Lima VM:
#     - nginx (proxy)              systemd service
#     - node (OpenClaw gateway)    systemd service per instance
#     - python (controller)        systemd service
#     - dockerd (tool sandbox)     for OpenClaw's built-in sandbox
#
# Usage:
#   ./sandbox/lima/setup.sh          # Full setup
#   ./sandbox/lima/setup.sh teardown # Remove everything
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CF_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# --- Configuration ---
LIMA_VM_NAME="clawfactory"
LIMA_DISK="100GiB"

# Sizing (generated by compute_sizing or defaults)
FC_SIZING_FILE="${CF_ROOT}/secrets/lima.sizing"
LIMA_CPUS=4
LIMA_MEMORY="8GiB"

# --- Helpers ---
info()  { printf "\033[1;34m[INFO]\033[0m  %s\n" "$*"; }
ok()    { printf "\033[1;32m[OK]\033[0m    %s\n" "$*"; }
warn()  { printf "\033[1;33m[WARN]\033[0m  %s\n" "$*"; }
err()   { printf "\033[1;31m[ERROR]\033[0m %s\n" "$*" >&2; }
die()   { err "$@"; exit 1; }

lima_exec() {
    limactl shell "$LIMA_VM_NAME" -- "$@"
}

lima_root() {
    limactl shell "$LIMA_VM_NAME" -- sudo bash -c "$1"
}

# ============================================================
# Compute resource sizing
# ============================================================
compute_sizing() {
    echo ""
    echo "=== Resource Sizing ==="
    echo ""
    echo "How many OpenClaw instances do you plan to run concurrently?"
    echo "Each instance needs ~2 GiB RAM (gateway + controller)."
    echo "Base VM overhead (kernel, nginx, Docker): ~2 GiB."
    echo ""
    read -p "Number of concurrent instances [1]: " instance_count
    instance_count="${instance_count:-1}"

    if ! [[ "$instance_count" =~ ^[0-9]+$ ]] || [[ "$instance_count" -lt 1 ]]; then
        warn "Invalid input, defaulting to 1"
        instance_count=1
    fi
    if [[ "$instance_count" -gt 8 ]]; then
        warn "Capping at 8 instances"
        instance_count=8
    fi

    # Lima VM: 2 GiB base + 2 GiB per instance
    local mem_gib=$(( 2 + instance_count * 2 ))
    LIMA_MEMORY="${mem_gib}GiB"

    # CPUs: 2 base + 1 per instance, capped at host-1
    local host_cpus
    host_cpus=$(sysctl -n hw.ncpu 2>/dev/null || echo 8)
    local max_cpus=$(( host_cpus - 1 ))
    [[ "$max_cpus" -lt 2 ]] && max_cpus=2
    LIMA_CPUS=$(( 2 + instance_count ))
    [[ "$LIMA_CPUS" -gt "$max_cpus" ]] && LIMA_CPUS="$max_cpus"

    mkdir -p "${CF_ROOT}/secrets"
    cat > "$FC_SIZING_FILE" <<EOF
# Lima VM sizing (auto-generated)
LIMA_INSTANCE_COUNT=${instance_count}
LIMA_CPUS=${LIMA_CPUS}
LIMA_MEMORY=${LIMA_MEMORY}
EOF
    chmod 600 "$FC_SIZING_FILE"

    echo ""
    info "Sizing for ${instance_count} instance(s):"
    info "  Lima VM: ${LIMA_CPUS} CPUs, ${LIMA_MEMORY} RAM, ${LIMA_DISK} disk"
    echo ""
}

# ============================================================
# Phase 1: Install Lima on macOS
# ============================================================
install_lima() {
    info "Phase 1: Installing Lima..."

    if ! command -v brew >/dev/null 2>&1; then
        die "Homebrew is required. Install from https://brew.sh"
    fi

    if command -v limactl >/dev/null 2>&1; then
        ok "Lima already installed: $(limactl --version)"
    else
        brew install lima
        ok "Lima installed: $(limactl --version)"
    fi
}

# ============================================================
# Phase 2: Create Lima VM
# ============================================================
create_lima_vm() {
    info "Phase 2: Creating Lima VM..."

    if limactl list -q 2>/dev/null | grep -q "^${LIMA_VM_NAME}$"; then
        local status
        status=$(limactl list --json 2>/dev/null | python3 -c "
import json,sys
for vm in json.loads(sys.stdin.read().rstrip().replace('}\n{', '},{')):
    if vm.get('name')=='$LIMA_VM_NAME': print(vm.get('status',''))
" 2>/dev/null || echo "unknown")
        if [ "$status" = "Running" ]; then
            ok "Lima VM '${LIMA_VM_NAME}' already running"
            return 0
        fi
        info "Starting existing Lima VM..."
        limactl start "$LIMA_VM_NAME"
        ok "Lima VM started"
        return 0
    fi

    info "Creating Lima VM '${LIMA_VM_NAME}' (VZ framework)..."
    info "  CPUs: ${LIMA_CPUS}, Memory: ${LIMA_MEMORY}, Disk: ${LIMA_DISK}"
    info "  This downloads an Ubuntu image and boots the VM (~1-3 minutes)..."
    echo ""

    local lima_yaml
    lima_yaml=$(mktemp /tmp/lima-cf-XXXXXX.yaml)
    cat > "$lima_yaml" <<YAML
vmType: vz
rosetta:
  enabled: false
cpus: ${LIMA_CPUS}
memory: "${LIMA_MEMORY}"
disk: "${LIMA_DISK}"
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
mounts: []
YAML

    limactl start --name="$LIMA_VM_NAME" "$lima_yaml"
    rm -f "$lima_yaml"

    ok "Lima VM created"
}

# ============================================================
# Phase 3: Install dependencies inside Lima VM
# ============================================================
install_dependencies() {
    info "Phase 3: Installing dependencies inside Lima VM..."

    info "Installing dependencies (this takes 2-5 minutes)..."
    echo ""

    # Step 1: Base packages
    echo -n "  [1/6] Base packages (ca-certificates, git, rsync, iptables)... "
    lima_root "
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qq >/dev/null 2>&1
        apt-get install -y -qq \
            ca-certificates curl gnupg lsb-release \
            iproute2 iptables \
            git rsync >/dev/null 2>&1
    "
    echo "done"

    # Step 1b: age
    lima_root "
        apt-get install -y -qq age 2>/dev/null || {
            ARCH=\$(dpkg --print-architecture)
            curl -fsSL \"https://dl.filippo.io/age/latest?for=linux/\${ARCH}\" -o /tmp/age.tar.gz
            tar -xzf /tmp/age.tar.gz -C /usr/local/bin/ --strip-components=1
            rm -f /tmp/age.tar.gz
        }
    " >/dev/null 2>&1

    # Step 2: Node.js
    echo -n "  [2/6] Node.js 22 + pnpm... "
    lima_root "
        export DEBIAN_FRONTEND=noninteractive
        if ! command -v node >/dev/null 2>&1; then
            curl -fsSL https://deb.nodesource.com/setup_22.x 2>/dev/null | bash - >/dev/null 2>&1
            apt-get install -y -qq nodejs >/dev/null 2>&1
        fi
        command -v pnpm >/dev/null 2>&1 || npm install -g pnpm >/dev/null 2>&1
    "
    echo "done ($(lima_exec node --version 2>/dev/null || echo '?'))"

    # Step 3: Python + controller deps
    echo -n "  [3/6] Python 3 + controller dependencies... "
    lima_root "
        export DEBIAN_FRONTEND=noninteractive
        apt-get install -y -qq python3 python3-pip python3-venv >/dev/null 2>&1
        pip3 install --break-system-packages --ignore-installed -q \
            fastapi uvicorn python-multipart httpx \
            PyGithub pyyaml docker python-jose 2>/dev/null
    "
    echo "done"

    # Step 4: Nginx
    echo -n "  [4/6] Nginx... "
    lima_root "
        export DEBIAN_FRONTEND=noninteractive
        apt-get install -y -qq nginx >/dev/null 2>&1
    "
    echo "done"

    # Step 5: Docker CE
    echo -n "  [5/6] Docker CE... "
    lima_root "
        export DEBIAN_FRONTEND=noninteractive
        if ! command -v docker >/dev/null 2>&1; then
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg 2>/dev/null | gpg --dearmor -o /etc/apt/keyrings/docker.gpg 2>/dev/null
            chmod a+r /etc/apt/keyrings/docker.gpg
            echo \"deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable\" \
                > /etc/apt/sources.list.d/docker.list
            apt-get update -qq >/dev/null 2>&1
            apt-get install -y -qq docker-ce docker-ce-cli containerd.io >/dev/null 2>&1
        fi
    "
    echo "done ($(lima_exec docker --version 2>/dev/null | cut -d' ' -f3 || echo '?'))"

    # Step 6: Enable services
    echo -n "  [6/6] Enabling services... "
    lima_root "systemctl enable docker nginx >/dev/null 2>&1"
    lima_root "apt-get clean >/dev/null 2>&1 && rm -rf /var/lib/apt/lists/*"
    echo "done"

    echo ""
    ok "All dependencies installed in Lima VM"
}

# ============================================================
# Phase 4: Create systemd unit templates and directory structure
# ============================================================
configure_services() {
    info "Phase 4: Configuring services..."

    lima_root "
        # ---- Directory structure ----
        mkdir -p /srv/clawfactory/{controller,proxy,bot_repos,secrets,audit,snapshots}

        # ---- Systemd unit: OpenClaw Gateway (template) ----
        # Port and state dir are set per-instance via overrides in lima_services()
        cat > /etc/systemd/system/openclaw-gateway@.service <<'SVC'
[Unit]
Description=OpenClaw Gateway (%i)
After=network.target docker.service
Wants=docker.service

[Service]
Type=simple
WorkingDirectory=/srv/clawfactory/bot_repos/%i/approved
EnvironmentFile=/srv/clawfactory/secrets/%i/gateway.env
Environment=OPENCLAW_STATE_DIR=/srv/clawfactory/bot_repos/%i/state/openclaw
ExecStart=/usr/bin/node dist/index.js gateway --bind lan
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SVC

        # ---- Systemd unit: ClawFactory Controller ----
        cat > /etc/systemd/system/clawfactory-controller.service <<'SVC'
[Unit]
Description=ClawFactory Controller
After=network.target

[Service]
Type=simple
WorkingDirectory=/srv/clawfactory/controller
ExecStart=/usr/bin/python3 -m uvicorn main:app --host 0.0.0.0 --port 8080
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SVC

        # ---- Default nginx config ----
        cat > /etc/nginx/sites-available/clawfactory <<'NGINX'
server {
    listen 80;
    server_name _;

    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_connect_timeout 60s;

    location / {
        proxy_pass http://127.0.0.1:18789;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \"upgrade\";
        proxy_buffering off;
        proxy_cache off;
    }

    location /health {
        proxy_pass http://127.0.0.1:18789/health;
    }
}

server {
    listen 8081;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /health {
        proxy_pass http://127.0.0.1:8080/health;
    }
}
NGINX

        rm -f /etc/nginx/sites-enabled/default
        ln -sf /etc/nginx/sites-available/clawfactory /etc/nginx/sites-enabled/clawfactory

        systemctl daemon-reload
    "

    ok "Services configured"
}

# ============================================================
# Teardown
# ============================================================
teardown() {
    info "Tearing down Lima sandbox..."

    if limactl list -q 2>/dev/null | grep -q "^${LIMA_VM_NAME}$"; then
        limactl stop "$LIMA_VM_NAME" 2>/dev/null || true
        limactl delete "$LIMA_VM_NAME" 2>/dev/null || true
        ok "Lima VM '${LIMA_VM_NAME}' deleted"
    else
        ok "Lima VM not found"
    fi

    if [[ -f "$FC_SIZING_FILE" ]]; then
        rm -f "$FC_SIZING_FILE"
        ok "Removed secrets/lima.sizing"
    fi

    ok "Lima sandbox fully cleaned up"
}

# ============================================================
# Main
# ============================================================
main() {
    echo ""
    echo "=========================================="
    echo " ClawFactory Lima Sandbox Setup"
    echo "=========================================="
    echo ""

    if [[ "$(uname)" != "Darwin" ]]; then
        die "This setup script is for macOS only (Lima + VZ framework)"
    fi

    # Load existing sizing or compute
    if [[ -f "$FC_SIZING_FILE" ]]; then
        source "$FC_SIZING_FILE"
        ok "Using existing sizing from secrets/lima.sizing"
    else
        compute_sizing
    fi

    install_lima
    create_lima_vm
    install_dependencies
    configure_services

    echo ""
    ok "=== Lima sandbox provisioned ==="
    echo ""
    echo "  Lima VM:   ${LIMA_VM_NAME} (${LIMA_CPUS} CPUs, ${LIMA_MEMORY})"
    echo "  Networking: VZ (near-native speed)"
    echo ""
    echo "  Start with:  ./clawfactory.sh -i <instance> start"
    echo "  SSH into VM: limactl shell ${LIMA_VM_NAME}"
    echo ""
}

case "${1:-setup}" in
    setup)    main ;;
    teardown) teardown ;;
    *)
        echo "Usage: $0 [setup|teardown]"
        echo ""
        echo "  setup     Provision Lima VM with dependencies (default)"
        echo "  teardown  Remove Lima VM and all data"
        exit 1
        ;;
esac
